# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sidetopiso.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#python -m PyQt5.uic.pyuic -x ui1.ui -o blog_script.py

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(604, 686)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(0, 0, 891, 531))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("../../Downloads/side view.PNG"))
        self.photo.setScaledContents(False)
        self.photo.setObjectName("photo")
        self.side = QtWidgets.QPushButton(self.centralwidget)
        self.side.setGeometry(QtCore.QRect(0, 530, 211, 121))
        self.side.setObjectName("side")
        self.top = QtWidgets.QPushButton(self.centralwidget)
        self.top.setGeometry(QtCore.QRect(210, 530, 211, 121))
        self.top.setObjectName("top")
        self.iso = QtWidgets.QPushButton(self.centralwidget)
        self.iso.setGeometry(QtCore.QRect(420, 530, 181, 121))
        self.iso.setObjectName("iso")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 604, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.top.clicked.connect(self.show_top)
        
        self.side.clicked.connect(self.show_side)
        
        self.iso.clicked.connect(self.show_popup)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.side.setText(_translate("MainWindow", "Side"))
        self.top.setText(_translate("MainWindow", "Top"))
        self.iso.setText(_translate("MainWindow", "Iso"))

    def show_top(self):
        self.photo.setPixmap(QtGui.QPixmap("Top view (1).PNG"))
        

    def show_side(self):
        self.photo.setPixmap(QtGui.QPixmap("side view.PNG"))
        
    def show_iso(self):
    
        self.photo.setPixmap(QtGui.QPixmap("isometric.PNG"))

    def show_popup(self):
        msg = QMessageBox()
        msg.setWindowTitle("Tutorial on PyQt5")
        msg.setText("This is the main text!")
        msg.setIcon(QMessageBox.Critical)
        msg.setStandardButtons(QMessageBox.Cancel|QMessageBox.Retry)
        msg.setDefaultButton(QMessageBox.Cancel)
        msg.setInformativeText("okayyyy")
        msg.setDetailedText("details")

        msg.buttonClicked.connect(self.popup_button)

        x = msg.exec_()
        
    def popup_button(self,i):
        print(i.text())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
